import { v4 as uuidv4 } from 'uuid';
import pinoHttp from 'pino-http';
import { requestLogger as pinoLogger } from '../lib/logger';
import { Request, Response, NextFunction } from 'express';

// Middleware to inject a unique request ID
export const requestIdMiddleware = (req: Request, res: Response, next: NextFunction) => {
  const reqId = req.headers['x-request-id'] || uuidv4();
  req.id = reqId;
  res.setHeader('X-Request-Id', reqId as string);
  next();
};

// Configured pino-http logger for Express
export const requestLogger = pinoHttp({
  logger: pinoLogger,
  genReqId: (req: any) => req.id, // Use the ID generated by our middleware
  customProps: (req: any, res: any) => {
    return {
      tenantId: req.user?.tenantId,
      userId: req.user?.id,
    };
  },
  customLogLevel: (req, res, err) => {
    if (res.statusCode >= 500 || err) return 'error';
    if (res.statusCode >= 400) return 'warn';
    return 'info';
  },
  customSuccessMessage: (req: any, res) => {
    return `${req.method} ${req.url} completed with status ${res.statusCode}`;
  },
  customErrorMessage: (req: any, res, err) => {
    return `${req.method} ${req.url} failed with status ${res.statusCode}: ${err.message}`;
  },
  // Don't log sensitive info from bodies/headers
  serializers: {
    req: (req) => {
      const sanitizedReq = {
        id: req.id,
        method: req.method,
        url: req.url,
        headers: {
          ...req.headers,
          authorization: req.headers.authorization ? '[REDACTED]' : undefined,
          cookie: req.headers.cookie ? '[REDACTED]' : undefined,
        },
        remoteAddress: req.remoteAddress,
      };
      return sanitizedReq;
    },
    res: (res) => ({
      statusCode: res.statusCode,
    }),
  },
});
